image:
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - x86
  - x64

install:
  - cmd: if %PLATFORM%==x64 (set PYTHON_ROOT=%PYTHON_ROOT%-x64)
  - cmd: set PATH=C:\ninja-build;%PYTHON_ROOT%\Scripts;%PYTHON_ROOT%;%PATH%
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" (call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %PLATFORM%)
  - cmd: if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%)
  - cmd: mkdir C:\ninja-build
  - ps: |
      (new-object net.webclient).DownloadFile('https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip', 'C:\ninja-build\ninja-win.zip')
  - cmd: 7z x -oC:\ninja-build C:\ninja-build\ninja-win.zip
  - cmd: pip3 install meson

before_build:
  - cmd: meson build
  - cmd: cd build

build_script:
  - cmd: ninja

test_script:
#  - cmd: ninja test

configuration:
  - Debug
  - Release

environment:
  matrix:
    - COVERAGE: 0
    - COVERAGE: 1
  PYTHON_ROOT: C:\\Python36

matrix:
  exclude:
    - configuration: Release
      COVERAGE: 1
